### ISSUE TITLE
No SSL at Admin Page

### ISSUE THREAD

**Issue by lalanikhurram** [shaan360/isssuelist#27]
Can you please activate SSL at admin page also.
![4](https://cloud.githubusercontent.com/assets/22701912/23855748/c86d6254-0818-11e7-931b-e85a98e5377b.png)

**Comment by munirsharif** [comment]
![image](https://cloud.githubusercontent.com/assets/22813867/23938475/54fefeb0-097e-11e7-8b73-a4515737fe0c.png)

**Comment by munirsharif** [comment]
its already activate on admin area too kindly check your click on lock icon and then give permission
