### ISSUE TITLE
Add profile png formate is not allowed

### ISSUE THREAD

**Issue by shaan360** [shaan360/isssuelist#7]
![6](https://cloud.githubusercontent.com/assets/803938/23329045/8ac8496a-fb51-11e6-8a34-fd3256c9aa15.PNG)

**Comment by munirsharif** [comment]
If user add any other file then message vl be same png not allowed that's why i put only Jpg format is allowed

**Comment by shaan360** [comment]
@munirsharif  I think all formats should be allowed.

**Comment by munirsharif** [comment]
JPeg and png use for image i think no need to allowed any other i think so kindly check again
